### ISSUE TITLE
Request for code

### ISSUE THREAD

**Issue by fahad92virgo** [lucidrains/zorro-pytorch#1]
Hi, I came across your paper and found it very interesting. It opens up a new direction for exploring multiple modalities. I would love to experiment with your framework. Could you please let me know the ETA on the code release

**Comment by zzl120** [comment]
me too

**Comment by liufangcen** [comment]
me too.

**Comment by lucidrains** [comment]
it'll be done this week, it is really simple actually

**Comment by lucidrains** [comment]
@fahad92virgo also, this isn't my paper, i just implement papers that i find are promising, so i'm in the same boat as you

**Comment by lucidrains** [comment]
ok, its done

**Comment by fahad92virgo** [comment]
Thank you so much. Really appreciate your contribution :)

**Comment by lucidrains** [comment]
@fahad92virgo no problem! hope you make some good discoveries
