### ISSUE TITLE
zorro_mask has order of operations bug

### ISSUE THREAD

**Issue by josiahbjorgaard** [lucidrains/zorro-pytorch#8]
https://github.com/lucidrains/zorro-pytorch/blob/fa2cd8137c15d82417637050ec872ef15cdb6982/zorro_pytorch/zorro_pytorch.py#L288

This line is incorrect as it first combines the mask and the token type matrix before comparing with the FUSION token enum value. It can be corrected to this:
```
zorro_mask = zorro_mask | (token_types_attend_from == TokenTypes.FUSION.value)
```

**Comment by HITzhongyu** [comment]
hi @josiahbjorgaard 
"After posing the question to you, I tried printing out the zorro_mask, and it appears to be like this: [[1,0,0],[1,1,1],[0,0,1]]. However, based on the paper, the zorro_mask should be [[1,1,0],[0,1,1],[0,1,0]], where [1,0,0] represents [audio, fusion, video]. 
hoping my understanding is correct and that this information helps you."

**Comment by lucidrains** [comment]
@josiahbjorgaard thank you Josiah!
